# Generated by Django 2.0.4 on 2018-08-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180817_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='slug',
        ),
    ]
