# Generated by Django 2.0.4 on 2018-08-17 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180817_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='alt',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
    ]
